name: CI

on:
  push:
    branches:
      - 'master'
    tags: [ 'v*' ]
  pull_request:
    branches:
      - 'master'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Test'
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        dotnet_sdk_version: [ '7.x' ]
        dotnet_runtime_version: [
          'net45', 'net46', 'net47', 'net48',
          'netstandard1.3', 'netstandard1.4', 'netstandard1.5',
          'netstandard1.6', 'netstandard2.0', 'netstandard2.1',
          'net5.0', 'net6.0', 'net7.0'
        ]
        python_version: [ '3.11' ]
        platform: [
          {
            os: 'macos-latest',
            python_architecture: 'x64'
          },
          {
            os: 'ubuntu-latest',
            python_architecture: 'x64'
          },
          {
            os: 'windows-latest',
            python_architecture: 'x64'
          },
        ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet_sdk_version }}
      - name: 'Run dotnet format'
        run: dotnet format style --verify-no-changes
      - name: 'Install CSharpier'
        run: dotnet tool install csharpier -g
      - name: 'Run CSharpier'
        run: dotnet csharpier --check .
      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.platform.python_architecture }}
      - name: 'Compare example from README with code'
        run: >
          python -c "import re;from pathlib import Path;
          raise SystemExit(
          '\n'.join(re.findall(r'(?<=```cs\n)([^`]+)', Path('README.md').read_text()))
          != Path('src/GonExamples/Basic.cs').read_text()
          )"
      - name: 'Install MyPy'
        run: python -m pip install mypy
      - name: 'Run MyPy'
        run: mypy --ignore-missing-imports tests
      - name: 'Install tests dependencies'
        run: python -m pip install -r requirements-tests.txt
      - name: 'Publish project'
        run: >
          dotnet publish --property:CheckEolTargetFramework=false 
          --property:PublishDir=$PWD/tests/ 
          --framework ${{ matrix.dotnet_runtime_version }} .
      - name: 'Run tests'
        run: pytest
